### ISSUE TITLE
Biased and Unbiased track resolution

### ISSUE THREAD

**Issue by TCThenna** [simonspa/resolution-simulator#4]
I think we could add a boolean to `getResolution()` offering to return biased and unbiased track resolutions. And points w/o measurements, this is implicit, but for points with measurements, I think at the moment always a biased track reso is returned. 

If you agree, I can do it at some point.

**Comment by simonspa** [comment]
Hm, but this you already get depending on whether you set the DUT as 
measurement or reference plane...

**Comment by TCThenna** [comment]
ok.
